version: "3"

services:
  postgres:
    container_name: postgres_cities
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cities

    ports:
      - "5432:5432"
